### ISSUE TITLE
a couple questions

### ISSUE THREAD

**Issue by outkaj** [Dwolla/scala-cloudflare#16]
1) what's the correct info for importing this library as a dependency? I saw the bintray is invalid and had some issues importing in `build.sbt`, using both the info on Maven, and info from the GitHub repo (for example, with
```"com.dwolla" % or %% "cloudflare-api-client_2.12" % "2.3.0"```
or 
```"com.github.Dwolla" (also tried "dwolla") % or %% "scala-cloudflare" % "2.4.0-SNAPSHOT"```)

2) what's the feature parity with Cloudflare API v4? I see the lib can query existing DNS records - can it also be used to update / add a new record? 

thanks very much for your help, and for the project!

**Comment by bpholt** [comment]
You should be able to import the `2.3.0` version using

```scala
resolvers ++= Seq(
  Resolver.bintrayRepo("dwolla", "maven")
)

libraryDependencies += "com.dwolla" %% "cloudflare-api-client" % "2.3.0"
```

(Some older versions were mistakenly published using Ivy-style packaging instead of Maven-style packaging, so another resolver needs to be added to import them, but as long as you want to use version 2.3 or later, `Resolver.bintrayRepo("dwolla", "maven")` should work.)

Right now, it supports [zone lookups](https://api.cloudflare.com/#zone-properties), [adding/updating/removing some record types from a zone](https://api.cloudflare.com/#dns-records-for-a-zone-properties), [rate limits](https://api.cloudflare.com/#rate-limits-for-a-zone-properties), and [account management for enterprise Cloudflare accounts](https://api.cloudflare.com/#accounts-properties).

FYI, we're in the process of switching the clients to use fs2 `Stream` to return data. I don't think this will impact how much of the Cloudflare v4 API is supported by this library, but some of the methods will have different semantics going forward. Once this is complete, we'll be expanding the record types that can be managed as well.

The functionality included in this library has been driven by what we need at Dwolla, so we have no plans to comprehensively cover Cloudflare's API. That said, PRs are welcome! 🙂

**Comment by outkaj** [comment]
@bpholt thanks for your quick reply! importing in the way you suggested worked. 

Those sound like a solid set of features. Right now, I'm mainly looking for adding/updating/removing some record types from a zone, so it seems like the library should cover that, but would certainly be willing to open a PR in future, if I end up needing to add a new feature. I've starred the project :)
